# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tyk < Formula
  desc "Command-line interface for managing Tyk APIs and configurations"
  homepage "https://github.com/sedkis/tyk-cli"
  version "0.2.2"
  license "MIT"

  depends_on "curl"

  on_macos do
    on_intel do
      url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.2/tyk-cli_0.2.2_darwin_amd64.tar.gz"
      sha256 "bb21b81544315fa3ee0154b9ae77822c9b251313dbe76916d39a130f397bb48d"

      def install
        bin.install "tyk"
      end
    end
    on_arm do
      url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.2/tyk-cli_0.2.2_darwin_arm64.tar.gz"
      sha256 "1e627673c96a071ca6301c9fff0ad36d61e98a3c5cedd118345cf13554282ebf"

      def install
        bin.install "tyk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.2/tyk-cli_0.2.2_linux_amd64.tar.gz"
        sha256 "de561bac8352bc7f941e0ef40d9984d2f9c8e4ff6486e25f3bfffa2f8ebef8a5"

        def install
          bin.install "tyk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.2/tyk-cli_0.2.2_linux_arm64.tar.gz"
        sha256 "f3b16d93f8405f9b95f62c15cb91c2e3e6db9bfd9176a8efc1ff9f2a44bf3beb"

        def install
          bin.install "tyk"
        end
      end
    end
  end

  test do
    system "#{bin}/tyk --version"
  end
end
