# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tyk < Formula
  desc "Command-line interface for managing Tyk APIs and configurations"
  homepage "https://github.com/sedkis/tyk-cli"
  version "0.2.1"
  license "MIT"

  depends_on "curl"

  on_macos do
    on_intel do
      url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.1/tyk-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "11b1c1ec0f5741f19e1e2fe1f1ea9d4d040b98c62a82798678b4ca1ace892727"

      def install
        bin.install "tyk"
      end
    end
    on_arm do
      url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.1/tyk-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "69fc404ef60d9267e99365877f8198bc2d6f8cec01ba5dd4bb60825d5df3d5a3"

      def install
        bin.install "tyk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.1/tyk-cli_0.2.1_linux_amd64.tar.gz"
        sha256 "f0bc972300d7a4152d91b6044261e829a7b5308a9804f9ec784a939778dcc7d2"

        def install
          bin.install "tyk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.1/tyk-cli_0.2.1_linux_arm64.tar.gz"
        sha256 "01e979b89d44f2f8d075e3c410d206845058a01018ff6c22a75a70f70fc3b66e"

        def install
          bin.install "tyk"
        end
      end
    end
  end

  test do
    system "#{bin}/tyk --version"
  end
end
