# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tyk < Formula
  desc "Command-line interface for managing Tyk APIs and configurations"
  homepage "https://github.com/sedkis/tyk-cli"
  version "0.2.4"
  license "MIT"

  depends_on "curl"

  on_macos do
    on_intel do
      url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.4/tyk-cli_0.2.4_darwin_amd64.tar.gz"
      sha256 "b9b034d720ff62bf9282c90cfd5e3697e43acda851b12c0f217b0354e1ff6536"

      def install
        bin.install "tyk"
      end
    end
    on_arm do
      url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.4/tyk-cli_0.2.4_darwin_arm64.tar.gz"
      sha256 "f730f41170c1b5f7dac9bb1762bb393d6975bc0197d734c88692842a3eeb47ea"

      def install
        bin.install "tyk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.4/tyk-cli_0.2.4_linux_amd64.tar.gz"
        sha256 "ea41dcd26570711d93ca3ab74b927b89cc48e197808420ec1a43f5b676b84682"

        def install
          bin.install "tyk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sedkis/tyk-cli/releases/download/v0.2.4/tyk-cli_0.2.4_linux_arm64.tar.gz"
        sha256 "0ba9c1662e2be77102dbacbfe1d46956c56aa64526ee00ea240ff25f1d83c204"

        def install
          bin.install "tyk"
        end
      end
    end
  end

  test do
    system "#{bin}/tyk --version"
  end
end
